services:

  kong-migrations:
    image: kong/kong-gateway:3.8.0.0 
    
    environment:
      - KONG_DATABASE=${KONG_DATABASE}
      - KONG_PG_HOST=${KONG_PG_HOST}
      - KONG_PG_PASSWORD=${KONG_PG_PASSWORD}
      - KONG_PASSWORD=${KONG_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - kong-net
    command:
      kong migrations bootstrap --v
    depends_on:
      - kong-database

  kong-database:
    image: postgres:15
    volumes:
      - pgdata:/data
    ports:
      - 5432:5432
    networks:
      - kong-net
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  cache:
    image: redis:latest
    command: redis-server
    volumes:
      - .:/data
    ports:
      - 6379:6379
  
  queing:
    image: rabbitmq:latest


    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/data

  kong-gateway:
    image: kong/kong-gateway:3.8.0.0

    command:
      kong start --v verbose
    environment:
      - KONG_DATABASE=${KONG_DATABASE}
      - KONG_PG_HOST=${KONG_PG_HOST}
      - KONG_PG_USER=${KONG_PG_USER}
      - KONG_PG_PASSWORD=${KONG_PG_PASSWORD}
      - KONG_PROXY_ACCESS_LOG=${KONG_PROXY_ACCESS_LOG}
      - KONG_ADMIN_ACCESS_LOG=${KONG_ADMIN_ACCESS_LOG}
      - KONG_PROXY_ERROR_LOG=${KONG_PROXY_ERROR_LOG}
      - KONG_ADMIN_ERROR_LOG=${KONG_ADMIN_ERROR_LOG}
      - KONG_ADMIN_LISTEN=${KONG_ADMIN_LISTEN}
      - KONG_ADMIN_GUI_URL=${KONG_ADMIN_GUI_URL}
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml

    depends_on:
      - kong-migrations

    ports:
      - 8443:8443
      - 8000:8000
      - 127.0.0.1:8444:8444
      - 127.0.0.1:8002:8002
      - 127.0.0.1:8001:8001
    networks:
      - kong-net

volumes:
  pgdata:
  rabbitmq_data:
  cache:
networks:
  kong-net: